version: "3.9"  # optional since v1.27.0
services:
  education_platform_client:
    profiles:
      - prod
    build: ./client/

  education_platform_server:
    profiles:
      - prod
    build: ./server/
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: diploma
      DB_USER: root
      DB_PASS: example

    links:
      - postgres

  postgres:
      image: postgres:11
      environment:
        POSTGRES_DB: diploma
        POSTGRES_USER: root
        POSTGRES_PASSWORD: example
      ports:
        - "5432:5432"
      volumes:
        - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data: {}
