import React, { useContext, useEffect, useState } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { AuthContext, AuthProvider } from '../../context/auth';
import Nav from '@/components/common/nav/top-layer1';
import { adminButtons, userButtons } from './page.layout.constants';
import SideBar from "@/components/common/nav/SideBar";

const Page = ({ title, children, tabs}:any) => {
  const router = useRouter();
  const { user }: any= useContext(AuthContext);

  useEffect(()=> {
    if(user != undefined
      && router.isReady
      && !!router.pathname.match('/admin')
      && user?.role !== 'admin') {

      router.push('/user/topics');
    }

  },[user?.role])

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div style={{
            margin: 'auto',
            maxWidth: '1920px',
            width: '100%'
        }}>
            <SideBar>
                {children}
            </SideBar>
        </div>

      {/*{!!router.pathname.match('/admin') ? <Nav buttons={adminButtons}/> : <Nav buttons={buttons}/>}*/}

      {/*<div style={{marginTop:"60px", width:'100%', height:"20px"}}></div>*/}
    </>
  );
};

export default Page;
