import React, { useContext, useEffect, useState } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { AuthContext, AuthProvider } from '../../context/auth';
import Nav from '@/components/common/nav';
import { adminButtons, userButtons } from './page.layout.constants';

const Page = ({ title, children, tabs, isAdmin }:any) => {
  const [buttons, setButtons] = useState(userButtons);
  const { user }: any= useContext(AuthContext);
  
  useEffect(()=> {
    setButtons(user?.role === 'admin' ? 
    [...buttons, { title:'Перейти в админку', href:'/admin' }] : 
    buttons.filter(el => el.href !== '/admin'));
  },[user?.role])

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isAdmin ? <Nav buttons={adminButtons}/> : <Nav buttons={buttons}/>}
      {children}
    </>
  );
};

export default Page;
