import React, { useContext, useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import { AuthContext } from "../../context/auth";
import Nav from "@/components/common/nav/top-layer1";
import buttons from "./page.layout.constants";
import { Container } from "semantic-ui-react";
import SideNav from "@/components/common/nav/sideNav";
import { TitlesProvider } from "@/context/titles";

const Page = ({ title, children }: any) => {
  const router = useRouter();
  const { user }: any = useContext(AuthContext);

  useEffect(() => {
    if (
      user != undefined &&
      router.isReady &&
      !!router.pathname.match("/admin") &&
      user?.role !== "admin"
    ) {
      router.push("/user/topics");
    }
  }, [user?.role]);

  if (!user?.role) return <div>...loading</div>;

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />

      <Container
        as="main"
        style={{
          flexGrow: 1,
          maxWidth: "720px",
          display: "flex",
          flexDirection: "column",
          alignItems: "flex-start",
          marginTop: "72px",
          position: "relative",
        }}
      >
        <TitlesProvider>
          <SideNav links={buttons?.[user?.role]}>{children}</SideNav>
        </TitlesProvider>
      </Container>
    </>
  );
};

export default Page;
